### ISSUE TITLE
A tutorial on how to use these scripts?

### ISSUE THREAD

**Issue by MarbleQ22** [prawigya/shiny-bot-pokemon#4]
Currently trying to get these scripts to work with no avail. I don't know how to run them and I'm not sure which ones to use for, say, Drifloon. Any *actual* help would be greatly appreciated!

**Comment by prawigya** [comment]
I've added the method to implement the bot in the ReadMe now, can you check it and try running it?

**Comment by MarbleQ22** [comment]
> I've added the method to implement the bot in the ReadMe now, can you check it and try running it?

Sure can! Thank you so, so much for updating!!

**Comment by MarbleQ22** [comment]
> I've added the method to implement the bot in the ReadMe now, can you check it and try running it?

Okay so Ive tried, sorry it took me a while, but I keep getting these specific errors when trying to run: 

"C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee>python screenshooter.py
Traceback (most recent call last):
  File "C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee\screenshooter.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee>python functions.py
Traceback (most recent call last):
  File "C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee\functions.py", line 2, in <module>
    from pynput.keyboard import Key, Controller
ModuleNotFoundError: No module named 'pynput'

C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee>python keyboard.py
Traceback (most recent call last):
  File "C:\Users\Marble\Desktop\Personal Files\AutoHunter\shiny-bot-pokemon-master\Combee\keyboard.py", line 2, in <module>
    from pynput.keyboard import Key, Controller
ModuleNotFoundError: No module named 'pynput'"

Any idea what those could mean?

**Comment by prawigya** [comment]
Yupp, this means that you don't have the libraries installed in your python env.
You can use [pip](https://realpython.com/what-is-pip/) to install them.

**Comment by norm1237** [comment]
Hi i am also having the same issue but i cant seem to figure out which libraries i need to install. 
Thanks you!

**Comment by norm1237** [comment]
> Hi i am also having the same issue but i cant seem to figure out which libraries i need to install. 
> 
> Thanks you!

NeverMind sorry ! I have figured it out and now it's working perfectly !

**Comment by MarbleQ22** [comment]
> > Hi i am also having the same issue but i cant seem to figure out which libraries i need to install.
> > Thanks you!
> 
> NeverMind sorry ! I have figured it out and now it's working perfectly !

Did you ever figure out which libraries? And how to properly install them? been trying for awhile now

**Comment by norm1237** [comment]
Hello ! Yes I have, I’m very new at python but figured out that reading the
codes like the screenshooter.py on top of it, it says input numpy, I looked
up what numpy was and I had to install it using pip on cmd not sure how it
would work on Mac though, all I did was pip install numpy and it would
automatically install. I did this with the other files it was imputing from
looking at the same file. But once you get all the files you shouldn’t get
a problem with it.! If you need anymore help let me know ! I know the whole
GitHub page was very confusing! It took me like 5 hrs just to figure it out
haha.
